version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: ["python", "server.py"]
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/test
    depends_on:
      - db

volumes:
  postgres_data:
